name: "Update Tag in GitHub Repo"
description: "Self use. Update the provided tag in the GitHub repo"
author: "Richard Simko"
inputs:
  tag_name:
    description: "Name of the tag to create or update"
    required: true
  ref:
    description: "Commit SHA, branch name, or tag name to create the tag from"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "tag"
  color: "green"
