name: CI
on: push

jobs:
  update-ref:
    name: Update reference
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION}}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Lint
        run: pnpm run lint
      - name: Get tag name
        id: extract-tag
        run: |
          TAG_NAME=${GITHUB_REF//\//-}
          echo "TAG_NAME=test-${TAG_NAME}" >> $GITHUB_OUTPUT
      - name: Update test tag
        uses: ./
        with:
          tag_name: ${{ steps.extract-tag.outputs.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
