name: Test Released Version
on:
  workflow_dispatch:

jobs:
  update-ref:
    name: Update reference
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION}}
      - name: Update test tag
        uses: greenhat616/update-tag@v1.2.2
        with:
          tag_name: test-released-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
